Esih_Drive/Esih_Drive/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('drive.views',
    url(r'^form/', include('login_register.urls')),
    url(r'^',  include('drive.urls', namespace='drive')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^books_cbv/', include('books_cbv.urls', namespace='books_cbv')),
    url(r'^books_fbv/', include('books_fbv.urls', namespace='books_fbv')),

    # url(r'^prop/(?P<id>\d+)$', 'get_fichier_prop', name='prop'),


)

# if debug is not true on deployment mode
if not settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if debug is true on deployment mode
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)', 'serve', {'document_root': settings.MEDIA_ROOT}), )

Esih_Drive/drive/urls.py
__author__ = 'jb-flo'

from django.conf.urls import patterns, url
from drive import views
from drive.views import DeleteFile


urlpatterns = patterns('drive.views',
        url(r'^$', views.index, name='index'),

        url(r'^prop/(?P<id>\d+)$', 'get_fichier_prop', name='prop'),
        url(r'^new/$',  'add_cours_prop', name='new'),
        url(r'^edit/(?P<pk>\d+)$',   views.UpdateFile.as_view(), name='edit_file'),
        url(r'^delete/(?P<pk>\d+)$', DeleteFile.as_view(), name='delete_file'),
)

Esih_Drive/drive/models.py
from django.db import models
from django.core.urlresolvers import reverse

# ///////////////////////////////////////////////////// Models CoursProp ///////////////////////////////////////////


class CoursProp(models.Model):
    prop_cours = models.CharField(max_length=42)

    def __unicode__(self):
        return self.prop_cours


class FichiersCoursProp(models.Model):
    cours_prop = models.ForeignKey(CoursProp)
    description_prop = models.CharField(max_length=100)
    doc_Prop = models.FileField(upload_to='DocumentProp/%Y/%m/%d')

    def __unicode__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('drive:edit', kwargs={'pk': self.pk})




# /////////////////////////////////////////////////   Old Modelds ////////////////////////////////////////////////

class Math (models.Model):
    name = models.CharField(max_length=50)
    doc_math = models.FileField(upload_to='maths/%Y/%m/%d')

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('drive:edit', kwargs={'pk': self.pk})

Esih_Drive/drive/forms.py
__author__ = 'jb-flo'

from django import forms
from drive.models import Math
from drive.models import FichiersCoursProp
from django.core.urlresolvers import reverse_lazy
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field
from crispy_forms.bootstrap import (
    PrependedText, PrependedAppendedText, FormActions)


class CoursPropForm(forms.ModelForm):
    class Meta:
        model = FichiersCoursProp


# ////////////////////////////////////////////////// old Forms ///////////////////////////////////////////////////////
class DocumentMath(forms.ModelForm):
    class Meta:
        model = Math
        label = 'Select a file',
        help_text = 'max. 42 megabytes'
        success_url = reverse_lazy('main')
        exclude = ('name',)
    helper = FormHelper()
    helper.form_method = 'POST'
    helper.add_input(Submit('upload', 'upload', css_class='btn-primary'))

Esih_Drive/drive/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response

from django.conf import settings
from django.shortcuts import redirect
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from drive.models import Math
from drive.forms import  DocumentMath

from django.shortcuts import render
from django.shortcuts import render_to_response
from django.http import Http404

from drive.forms import CoursPropForm

from django.core.context_processors import csrf

from drive.models import CoursProp
from drive.models import FichiersCoursProp
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import DeleteView

# Create your views here.


def index(request):
    if not request.user.is_authenticated():
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    else:
        return render(request, 'drive/index.html')

# /////////////////////////////////////////////// Views Prop ///////////////////////////////////////////////////////////

# abc change to  get_coursProp

def get_coursProp(request):
    add = CoursPropForm()
    cours_prop = CoursProp.objects.all()
    return render(request, 'drive/prop.html', locals())

# adcd change to get_fichierProp

def get_fichier_prop(request, id):
    try:
        cours = CoursProp.objects.all()
        cours_prop = CoursProp.objects.get(id=id)
        doc_Prop = FichiersCoursProp.objects.filter(cours_prop=id)
    except FichiersCoursProp.DoesNotExist:
        raise Http404
    if not request.user.is_authenticated():
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    else:
        return render(request, 'drive/prop.html', locals())


def add_cours_prop(request):
    registered = False
    if request.method == 'POST':
        form_prop = CoursPropForm(request.POST, request.FILES)
        if form_prop.is_valid():
            cours_prop = request.POST['cours_prop']
            doc_Prop = form_prop.cleaned_data['doc_Prop']
            form_prop.save()
            registered = True
            return render(request, 'drive/new.html', locals())
        else:
            print(form_prop.errors)
    else:
        form_prop = CoursPropForm()
        var = {'form_prop': form_prop}
        var.update(csrf(request))

    if not request.user.is_authenticated():
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    else:
        return render_to_response('drive/new.html', var)

class UpdateFile(UpdateView):
    template_name = 'drive//new.html'
    model = FichiersCoursProp
    success_url = reverse_lazy('/prop/1')

class DeleteFile (DeleteView):
    template_name = 'drive/delete.html'
    model = FichiersCoursProp
    success_url = '/get_coursProp/id'








# ////////////////////////////////////////////////  Old Views  ////////////////////////////////////////////////////////



class PropMath(ListView):
      template_name = 'drive/prop.html'
      model = Math

class PropCreateMath(CreateView):
    template_name = 'drive/new.html'
    model = Math
    success_url = reverse_lazy('drive:prop')

class PropUpdateMath(UpdateView):
    template_name = 'drive/new.html'
    model = Math
    success_url = reverse_lazy('drive:prop')


class PropDeleteMath(DeleteView):
    template_name = 'drive/delete.html'
    model = Math
    success_url = reverse_lazy('drive:prop')

# ////////////////////////////////////////////////////////////////////////////////////////////////


# def prop(request):
#     # Handle file upload
#     if request.method == 'POST':
#         form = DocumentMath(request.POST, request.FILES)
#         if form.is_valid():
#             newdoc_math = Math(doc_math=request.FILES['doc_math'])
#             newdoc_math.save()
#             # form.save()
#
#         form1 = DocumentMethodologie(request.POST, request.FILES)
#         if form1.is_valid():
#             newdoc_meth = Methodologie(doc_methodologie=request.FILES['doc_methodologie'])
#             newdoc_meth.save()
#             # form1.save()
#
#             # Redirect to the document list after POST
#         return HttpResponseRedirect(reverse('drive.views.prop'))
#     else:
#         form = DocumentMath()  # A empty, unbound form
#         form1 = DocumentMethodologie()
#
#     # Load documents for the list page
#     maths = Math.objects.all()
#     methodologie = Methodologie.objects.all()
#
#     # Render list page with the documents and the form
#     if not request.user.is_authenticated():
#         return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
#     else:
#         return render_to_response(
#             'drive/prop.html', locals(), context_instance = RequestContext(request)
#
#             )
#
# def delete_document(request, pk):
#     try:
#         Math.objects.get(pk=pk).delete()
#     except Math.DoesNotExist:
#         pass
#     return HttpResponseRedirect('drive.views.l1')

Esih_Drive/templates/drive/delete.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

   <form method="post">
        {% csrf_token %}
        Are you sure you want to delete "{{ object }}" ?
        <input type="submit" value="Submit" />
  </form>

{# <a href="{% url "drive:prop" %}">Retour </a>#}
 <a href="/prop/1"> Retour </a>

</body>
</html>

Esih_Drive/templates/drive/multiuploader_main.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

{% load thumbnail %}

<h1><a href="{% url multi %}">Multiuploader</a></h1>
<br />
<h2>Images:</h2>
<hr>
<div class="photos">
{% for item in items %}
{% thumbnail item "80x80" crop="10px 10px" as im %}
    <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
{% endthumbnail %}
{% endfor %}
</div>
<hr>

</body>
</html>

Esih_Drive/templates/drive/new.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
   <title>ESIH DRIVE / DOWNLOAD CENTER </title>
    <link rel="shortcut icon" href="{% static "images/Icon_drive.jpg" %}"  type="image/x-icon">
    <meta name="description" content=" System file sharing ,where student can download, and prof can upload file on the plateform " />

    <link rel="stylesheet" href="{% static "css/fonts.css" %}" />

    <link rel="stylesheet" href="{% static "css/normalize.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/main.css" %}" />
    <link rel="stylesheet" href="{% static "css/respond-480-tablet.css" %}" />
    <link rel="stylesheet" href="{% static "css/respond-768-laptop.css" %}" />
    <link rel="stylesheet" href="{% static "css/respond-1140-deskop.css" %}" />

    <link rel="stylesheet" href="{% static "css/header.css" %}" />
    <link rel="stylesheet" href="{% static "css/footer.css" %}" />
    <link rel="stylesheet" href="{% static "css/leftnav.css" %}" />
    <link rel="stylesheet" href="{% static "css/simpletree.css" %}" />
    <link rel="stylesheet" href="{% static "css/home.css" %}" />

    <link rel="stylesheet" href="{% static "css/jquery-ui-1.10.4.custom.css" %}" />



    <script src="{% static "js/header.js" %}" ></script>


    <link rel="stylesheet" href="{% static "css/bootstrap-panel.css" %}" />
    <link rel="stylesheet" href="{% static "css/bootstrap-carousel.css" %}" />

    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}" />
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" />
</head>
<body>

    <header>

        <div class="color-bar-1"></div>
        <div class="color-bar-2 color-bg"></div>

      <div class="w1024 center" style="height:65px; display:block;">
           <a href="/prop/1" class="drive-logo-home"> <img src="{% static "images/logo_drive.png" %}" alt="Esih_Drive download center" style=" width:500px; height:60px; max-width: none;" /> </a>

        <div id="headernav" class="glyph">
            <ul>
                <li id="login">
                 {% if user.is_authenticated %}
                     <h2>Welcome {{ user.username }}!</h2>
                  {% else %}
                     <h2> Not connect </h2>
                 {% endif %}

                </li>
             </ul>
        </div>
        </div>

    </header>

<br />
<br />
<br />
<br />
<br />
<br />

    <div class="container">
<h1> Here You ----> <span style="color: #145c93">{{ user.username }} </span> Can Upload File TO Server </h1>

      <div id="login">

{#     {% if user.is_authenticated and perms.drive %}#}
         <form  method="post" enctype="multipart/form-data">
             {% csrf_token %}
             {{ form_prop.as_p }}
             <br />
             <input type="submit" value="UPLOAD" css_class='btn-primary'  />
         </form>

{#        {% else %}#}
                     <h3> you can't  upload file</h3>

{#        {% endif %}#}
 </div> <!-- end login -->

    </div>


</body>
</html>

Esih_Drive/templates/drive/new1.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
 <title>ESIH DRIVE / DOWNLOAD CENTER </title>
    <link rel="shortcut icon" href="{% static "images/Icon_drive.jpg" %}"  type="image/x-icon">
    <meta name="description" content=" System file sharing ,where student can download, and prof can upload file on the plateform " />




    <link rel="stylesheet" href="{% static "css/fonts.css" %}" />

    <link rel="stylesheet" href="{% static "css/normalize.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/main.css" %}" />
    <link rel="stylesheet" href="{% static "css/respond-480-tablet.css" %}" />
    <link rel="stylesheet" href="{% static "css/respond-768-laptop.css" %}" />
    <link rel="stylesheet" href="{% static "css/respond-1140-deskop.css" %}" />

    <link rel="stylesheet" href="{% static "css/header.css" %}" />
    <link rel="stylesheet" href="{% static "css/footer.css" %}" />
    <link rel="stylesheet" href="{% static "css/leftnav.css" %}" />
    <link rel="stylesheet" href="{% static "css/simpletree.css" %}" />
    <link rel="stylesheet" href="{% static "css/home.css" %}" />

    <link rel="stylesheet" href="{% static "css/jquery-ui-1.10.4.custom.css" %}" />



    <script src="{% static "js/header.js" %}" ></script>


    <link rel="stylesheet" href="{% static "css/bootstrap-panel.css" %}" />
    <link rel="stylesheet" href="{% static "css/bootstrap-carousel.css" %}" />

    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}" />
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" />
</head>
<body>

    <header>

        <div class="color-bar-1"></div>
        <div class="color-bar-2 color-bg"></div>

      <div class="w1024 center" style="height:65px; display:block;">
           <a href="{% url "drive:prop" %}" class="drive-logo-home"> <img src="{% static "images/logo_drive.png" %}" alt="Esih_Drive download center" style=" width:500px; height:60px; max-width: none;" /> </a>

        <div id="headernav" class="glyph">
            <ul>
                <li id="login">
{#                <a href="# id="signInLink"><img src="dcommon/img/sign-on.png" width="14" height="5" alt="Sign In Icon" style="vertical-align: text-bottom;"/> Sign In</a>#}
{#                    <a href="#" id="signInLink"><img src="dcommon/img/sign-on.png" width="14" height="19" alt="Sign In Icon" style="vertical-align: text-bottom;"/> SIGN IN</a>#}
                  {% if user.is_authenticated %}
                     <h2>Welcome {{ user.username }}!</h2>
                  {% else %}
                     <h2>ESIH_DRIVE</h2>
                  {% endif %}
                </li>
             </ul>
        </div>
        </div>

    </header>

<br />
<br />
<br />
<br />
<br />
<br />

    <div class="container">
<h1> Here You ----> <span style="color: #145c93">{{ user.username }} </span>Can Upload File TO Server  </h1>

      <div id="login">

     {% if user.is_authenticated and perms.drive %}
           <form method="post" enctype="multipart/form-data">
               {% csrf_token %}
                {{ form.as_p}}
               <br />
               <input type="submit" value="UPLOAD" css_class='btn-primary' />
           </form>
        {% else %}
                     <h3> you can't  upload file</h3>

        {% endif %}
 </div> <!-- end login -->

    </div>

</body>
</html>

Esih_Drive/templates/drive/prop.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html lang="en" class="no-js" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html"> <!--<![endif]-->

{% load staticfiles %}
{% load crispy_forms_tags %}
<head lang="en">
    <meta charset="UTF-8">
    <title>ESIH DRIVE / DOWNLOAD CENTER </title>
    <link rel="shortcut icon" href="{% static "images/Icon_drive.jpg" %}"  type="image/x-icon">
    <meta name="description" content=" System file sharing ,where student can download, and prof can upload file on the plateform " />




    <link rel="stylesheet" href="{% static "css/fonts.css" %}" />

    <link rel="stylesheet" href="{% static "css/normalize.min.css" %}" />
    <link rel="stylesheet" href="{% static "css/main.css" %}" />
    <link rel="stylesheet" href="{% static "css/respond-480-tablet.css" %}" />
    <link rel="stylesheet" href="{% static "css/respond-768-laptop.css" %}" />
    <link rel="stylesheet" href="{% static "css/respond-1140-deskop.css" %}" />

    <link rel="stylesheet" href="{% static "css/header.css" %}" />
    <link rel="stylesheet" href="{% static "css/footer.css" %}" />
    <link rel="stylesheet" href="{% static "css/leftnav.css" %}" />
    <link rel="stylesheet" href="{% static "css/simpletree.css" %}" />
    <link rel="stylesheet" href="{% static "css/home.css" %}" />

    <link rel="stylesheet" href="{% static "css/jquery-ui-1.10.4.custom.css" %}" />



    <script src="{% static "js/jquery-1.10.2.js" %}" ></script>

    <script src="{% static "js/jquery-ui-1.10.4.custom.js" %}" ></script>
    <script src="{% static "css/jquery-ui-1.10.4.custom.css" %}" ></script>

    <script src="{% static "js/header.js" %}" ></script>
    <script src="{% static "js/tabs.js" %}" ></script>
    <script src="{% static "js/booklist.js" %}" ></script>
    <script src="{% static "js/leftnav.js" %}" ></script>


    <script src="{% static "js/jquery-1.11.0.min.js" %}" ></script>
    <script src="{% static "js/modernizr-2.6.1-respond-1.1.0.min.js" %}" ></script>
    <!--<script src="{% static "js/common.js" %}" ></script>-->
    <script src="{% static "js/search.js" %}" ></script>
    <script src="{% static "js/bootstrap.min.js" %}" ></script>


    <!--bootstrap components-->

    <link rel="stylesheet" href="{% static "css/bootstrap-panel.css" %}" />
    <link rel="stylesheet" href="{% static "css/bootstrap-carousel.css" %}" />

    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}" />
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" />


</head>


<body id="propbody"  class="cloud-body category-page">
<!--this body tag is only needed to highlight the navigation for demo-->

    <header>

        <div class="color-bar-1"></div>
        <div class="color-bar-2 color-bg"></div>

      <div class="w1024 center" style="height:65px; display:block;">
           <a href="{% url "drive:index" %}" class="drive-logo-home"> <img src="{% static "images/logo_drive.png" %}" alt="Esih_Drive download center" style=" width:500px; height:60px; max-width: none;" /> </a>

        <div id="headernav" class="glyph">
            <ul>
                <li id="login">
{#                <a href="# id="signInLink"><img src="dcommon/img/sign-on.png" width="14" height="5" alt="Sign In Icon" style="vertical-align: text-bottom;"/> Sign In</a>#}
{#                    <a href="#" id="signInLink"><img src="dcommon/img/sign-on.png" width="14" height="19" alt="Sign In Icon" style="vertical-align: text-bottom;"/> SIGN IN</a>#}
                  {% if user.is_authenticated %}
                     <h2> Welcome {{ user.username }}!</h2>
                  {% else %}
                     <h2>ESIH_DRIVE</h2>
                  {% endif %}
                </li>
             </ul>
        </div>
        </div>

    </header>

 <!--<script src="{% static "js/helpdrawer.js" %}" ></script>-->
      <!--<script src="../dcommon/js/helpdrawer.js"></script>-->

<!-- The content -->

    <div id="content" style="margin-top: 63px;">
        <div class="left-nav" style="display: block;">

            <ul>
                <li><a id="Home" href="/drive">
                    <img src="{% static "images/arrow-left.png" %}" alt="home" width="14" height="15"  style="vertical-align: text-bottom;"/> Home</a>
                </li>
                <li><a id="prop" href="/drive/prop">Propédeutique</a></li>
                <li><a id="l1" href="/drive/l1">1ère Année info</a></li>
                <li><a id="l2" href="/drive/l2" class="selected">2ème Année info</a></li>
                <li><a id="l3" href="/drive/l3">3ème Année info</a></li>
                <li><a id="m1_b" href="/drive/m1">M1 Data Base</a></li>
                <li><a id="m1_t"  href="/drive/m1t">M1 Telecom</a></li>
                <li><a id="l1_eco" href="/">1ère Année Economie Gestion</a></li>
                <li><a id="l1_eco" href="">2ème Année Economie & Gestio</a></li>
                <li><a id="l3_eco" href="">3ème Année Economie & Gestio</a></li>
                <li><a id="m1_eco" href="">M1 Economie & Gestion</a></li>
                <li><a id="m1_sc" href="">M1 Science Comptable </a></li>
                <li><a id="mone"   href=""> Mone </a></li>
                <li><a id="all" href="">All Documents And Course</a></li>

            </ul>
        </div>

        <div id="shownav" title="Show Navigation" style="display: none;"></div>
        <div id="hidenav" style="display: none;"></div>
        <div id="main" class="main-pad" style="margin-left: 160px;">
        <script src="../dcommon/js/helpdrawer.js"></script>

      	<!--start help drawer -->

       <div id="helpdrawer" class="border-left shadow" style="right: -280px;">

          <div id="helptab" class="border "></div>

        <!--end help drawer contents -->
        </div>

<!--end help drawer -->

        <img class="img-right" src="{% static "images/EsihDriveprop.png" %}" width="230" height="190" alt="LOGO PAGE" />
        <h1>Propedeutique Documentations</h1>

        <p> Vous etre en année preparatoire? Vous avez ici l'accès a tous les cours de niveau 0 Disponibles</p>
    <div class="tabs">
        <ul class="tab-links">
{#            <a href="#tab1">Math</a>#}

             {% for name in cours %}
               <li class=""><a href = "{% url "drive:prop" name.id %}"> {{name.prop_cours}}</a> </li>
             {% endfor %}

{#		    <li><a href="#tab8">etc...</a></li>#}

        </ul>
    <div class="tab-content">

     <div class="tab" id="tab1" style="display: none;">

{#               <li><a href="{{ DocumentMath.doc_math.url }}">{{ DocumentMath.doc_math.name }}</a>#}
{#                    {% if user.is_authenticated and perms.drive %}#}
{#                     <a href="{% url "drive:edit" DocumentMath.id %}"> <span style=" color: #f0ad4e; margin-left: 15px;"> EDIT</span> </a>#}
{#                     <a href="{% url "drive:delete" DocumentMath.id %}"> <img src="{% static "images/delete.png" %}" width="20" height="20" alt="Delete" /></a>#}
{#                    {% endif %}#}
{#                </li>#}
       {% for fichiers in doc_Prop%}
           <li>

                {{fichiers.doc_Prop.url}}
{#                {{fichiers.id}}<br/>#}
                {{fichiers.description_prop}}
                <a href="{% url "drive:edit_file" fichiers.id %}"> <span style=" color: #f0ad4e; margin-left: 15px;"> EDIT</span> </a>
                <a href = "{% url "drive:delete_file" fichiers.id%}">   <img src="{% static "images/delete.png" %}" width="20" height="20" alt="Delete" /></a>
           </li>
       {% endfor%}


           {% if user.is_authenticated and perms.drive %}
            <a href="{% url "drive:new" %}"> ADD NEW DOC </a>
           {% else %}
                <h3> you can't  upload file</h3>

            {% endif %}



{##}
{#         {% if math_list %}#}
{#			<ul>#}
{#                {% for DocumentMath in math_list %}#}
{#				<li><a href="{{ DocumentMath.doc_math.url }}">{{ DocumentMath.doc_math.name }}</a>#}
{#                    {% if user.is_authenticated and perms.drive %}#}
{#                     <a href="{% url "drive:edit" DocumentMath.id %}"> <span style=" color: #f0ad4e; margin-left: 15px;"> EDIT</span> </a>#}
{#                    <a href="{% url "drive:delete" DocumentMath.id %}"> <img src="{% static "images/delete.png" %}" width="20" height="20" alt="Delete" /></a>#}
{#                    {% endif %}#}
{#                </li>#}
{#			{% endfor %}#}
{#			</ul>#}
{#		{% else %}#}
{#			<p> No Maths documents. </p>#}
{#		{% endif %}#}
{#        <br />#}
{##}
{#        {% if user.is_authenticated and perms.drive %}#}
{#           <a href="{% url "drive:new" %}"> ADD NEW DOC </a>#}
{#        {% else %}#}
{#                     <h3> you can't  upload file</h3>#}
{##}
{#        {% endif %}#}


     </div>


    <div id="tab2" class="tab" style="display: none;">
       {% if methodologie_list %}
			<ul>
                {% for DocumentMethodologie in methodologie_list%}
				    <li><a href="{{ DocumentMethodologie.doc_methodologie.url }}">{{ DocumentMethodologie.doc_methodologie.name}}</a>
                    {% if user.is_authenticated and perms.drive %}
                     <a href="{% url "drive:edit" DocumentMethodologie.id %}"> <span style=" color: #f0ad4e; margin-left: 15px;"> EDIT</span> </a>
                     <a href="{% url "drive:delete" DocumentMethodologie.id %}"> <img src="{% static "images/delete.png" %}" width="20" height="20" alt="Delete" /></a>
                    {% endif %}
                </li>
			{% endfor %}
			</ul>
		{% else %}
			<p> No Methodologie documents. </p>
		{% endif %}
        <br />

        {% if user.is_authenticated and perms.drive %}
{#           <a href="{% url "drive:new1" %}">ADD NEW DOC </a>#}
        {% else %}
                     <h3> you can't  upload file</h3>

        {% endif %}


    </div>

    <div id="tab3" class="tab" style="display: block;">

    </div>

  <div id="tab4" class="tab" style="display: none;">


  </div>

  <div id="tab5" class="tab" style="display: none;">

  </div>

  <div id="tab6" class="tab" style="display: none;">

  </div>
  <div id="tab8" class="tab" style="display: none;">

  </div>

  <div id="tab7" class="tab" style="display: none;">

  </div>

 </div>
</div>

     <br class="clearfloat">


       <br style="clear:both;">
       <br>
        </div>
</div>


     <footer></footer>


 </body>

</html>     

Esih_Drive/templates/drive/test.html
{#{% extends "drive/prop.html" %}#}
{#{% extends "drive/l1.html" %}#}

Esih_Drive/templates/drive/test2.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

         {% if documents %}
			<ul>
			{% for document in documents %}
				<li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
			{% endfor %}
			</ul>
		{% else %}
			<p> No documents. </p>
		{% endif %}

        {% block test %} {% endblock %}
</body>
</html>