Esih_Drive/Esih_Drive/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('drive.views',
    url(r'^form/', include('login_register.urls')),
    url(r'^',  include('drive.urls', namespace='drive')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^books_cbv/', include('books_cbv.urls', namespace='books_cbv')),
    url(r'^books_fbv/', include('books_fbv.urls', namespace='books_fbv')),

    # url(r'^prop/(?P<id>\d+)$', 'get_fichier_prop', name='prop'),


)

# if debug is not true on deployment mode
if not settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if debug is true on deployment mode
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'media/(?P<path>.*)', 'serve', {'document_root': settings.MEDIA_ROOT}), )

Esih_Drive/books_cbv/urls.py
from django.conf.urls import patterns, url

from books_cbv import views

urlpatterns = patterns('',
  url(r'^$', views.BookList.as_view(), name='book_list'),
  url(r'^new$', views.BookCreate.as_view(), name='book_new'),
  url(r'^edit/(?P<pk>\d+)$',   views.BookUpdate.as_view(), name='book_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.BookDelete.as_view(), name='book_delete'),
)

Esih_Drive/drive/urls.py
__author__ = 'jb-flo'

from django.conf.urls import patterns, url
from drive import views
from drive.views import DeleteFile


urlpatterns = patterns('drive.views',
        url(r'^$', views.index, name='index'),

        url(r'^prop/(?P<id>\d+)$', 'get_fichier_prop', name='prop'),
        url(r'^new/$',  'add_cours_prop', name='new'),
        url(r'^edit/(?P<pk>\d+)$',   views.UpdateFile.as_view(), name='edit_file'),
        url(r'^delete/(?P<pk>\d+)$', DeleteFile.as_view(), name='delete_file'),
)

Esih_Drive/books_cbv/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()
    doc_math = models.FileField(upload_to='maths/%Y/%m/%d')

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_cbv:book_edit', kwargs={'pk': self.pk})

Esih_Drive/books_cbv/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from books_cbv.models import Book


class BookList(ListView):
    model = Book


class BookCreate(CreateView):
    model = Book
    success_url = reverse_lazy('books_cbv:book_list')


class BookUpdate(UpdateView):
    model = Book
    success_url = reverse_lazy('books_cbv:book_list')


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books_cbv:book_list')

Esih_Drive/books_cbv/templates/books_cbv/book_confirm_delete.html
<form method="post">
    {% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

Esih_Drive/books_cbv/templates/books_cbv/book_form.html
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"  />
</form>

Esih_Drive/books_cbv/templates/books_cbv/book_list.html
<h1>Books CBV</h1>
<ul>
    {% for book in object_list %}
    <li><a href="{{ book.url }}"> {{ book.name }} </a> :
    <a href="{% url "books_cbv:book_edit" book.id %}">{{ book.pages }}</a>
    <a href="{% url "books_cbv:book_delete" book.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url "books_cbv:book_new" %}">New</a>